spring:
  application:
    name: api-gateway
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest  

env:
  profile: dev
  label: master
  version: 1.0.0



# 关闭安全校验
management:
  endpoints:
    web:
      exposure:
        include: "*"
