spring:
  application:
    name: api-gateway
  redis:
    host: 192.168.99.100
    port: 6379       
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest  

env:
  profile: dev
  label: master
  version: 1.0.1

# path: 路由规则
# serviceId: 代理哪个服务
# sensitiveHeaders: 默认过滤headers的某些key，比如["Cookie", "Set-Cookie", "Authorization"], 这里设置为空，不过滤
# ignored-patterns:排除某些路由，不暴露给客户端
# host下的两个超时配置 以url请求时会生效
zuul:
  host:
    connect-timeout-millis: 60000 # HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 60000   #socket超时
  sensitive-headers: 
  routes:
    proxy-product:
      path: /api/product/**
      serviceId: biz-product
    proxy-order:
      path: /api/order/**
      serviceId: biz-order
    proxy-user:
      path: /api/user/**
      serviceId: biz-user
 # ignored-patterns:排除某些路由，不暴露给客户端
  ignored-patterns:
    - /**/product/listForOrder
    - /**/product/decreaseStock
    - /config-server/**

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

            
# 关闭安全校验
management:
  endpoints:
    web:
      exposure:
        include: "*"
