server:
  port: 9001

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/springcloud_demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      validation-query: SELECT 1
      filters: stat,wall,config
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest      
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

env:
  profile: dev
  label: master
  version: 1.0.1
  
##指定负载均衡策略
#biz-product:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
