spring:
  application:
    name: biz-user
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/springcloud_demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      validation-query: SELECT 1
      filters: stat,wall,config
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"
  redis:
    host: 192.168.99.100
    port: 6379      
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest  
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

env:
  profile: dev
  label: master
  version: 1.0.1
  
# 自定义属性 保存在cookies的token名和过期时间
user:
  token-key: X-token
  expire: 7200
